server:
  port: ${port:8080}
  error:
    include-message: always
logging:
  level:
    web: debug
management:
  endpoint:
    gateway:
      enabled: true
spring:
  config:
    import: classpath:env.properties
  application:
    name: GraalGatewayTest
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENTID}
            clientSecret: ${GOOGLE_CLIENTSECRET}
            redirect-uri: https://595e-2804-56c-a093-1200-cd43-9996-4ff7-8730.ngrok-free.app/login/oauth2/code/google
            scope:
              - email
              - profile
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      routes:
        - id: blog
          uri: http://localhost:8088
          predicates:
            - Path=/person/**
          filters:
            - AddRequestHeader=X-Tenant,acme
            - AddResponseHeader=X-Genre,fantasy
