spring:
  application:
    name: GraalGatewayTest
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 479928121921-534fdtkvc7ts1q4fogv4au3l7t2m2220.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  cloud:
    gateway:
      routes:
        - id: blog
          uri: http://localhost:8088
          predicates:
            - Path=/person/**