spring:
  application:
    name: GraalGatewayTest
  cloud:
    gateway:
      routes:
        - id: blog
          uri: http://localhost:8088
          predicates:
            - Path=/person/**
          filters:
            - AddRequestHeader=X-Tenant,acme
            - AddResponseHeader=X-Genre,fantasy