server:
  port: ${port:8081}
  error:
    include-message: always
logging:
  level:
    web: debug
management:
  endpoint:
    gateway:
      enabled: true
spring:
  config:
    import: classpath:env.properties
  application:
    name: GraalGatewayTest
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
      client:
        provider:
          keycloak:
            issuerUri: http://localhost:8080/realms/SpringBootKeycloak
            userNameAttribute: preferred_username
        registration:
          keycloak:
            clientId: loginApp
            authorizationGrantType: authorization_code
            scope:
              - openid
          google:
            clientId: ${GOOGLE_CLIENTID}
            clientSecret: ${GOOGLE_CLIENTSECRET}
            redirect-uri: https://d20a-2804-56c-a1d8-8900-d4dc-d205-e535-3574.ngrok-free.app/login/oauth2/code/google
            scope:
              - email
              - profile
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  cloud:
    gateway:
      routes:
        - id: blog
          uri: http://localhost:8088
          predicates:
            - Path=/person/**
          filters:
            - AddRequestHeader=X-Tenant,acme
            - AddResponseHeader=X-Genre,fantasy
